short_venue_names = {
 'The American Economic Review': 'Am. Econ. Rev.',
 'Journal of Political Economy': 'J. Polit. Econ.',
 'Quarterly Journal of Economics': 'Q. J. Econ.',
 'Management Science': 'Manage. Sci.',
 'Academy of Management Journal': 'Acad. Manage. J.',
 'Administrative Science Quarterly': 'Adm. Sci. Q.',
 'American Sociological Review': 'Am. Sociol. Rev.',
 'American Journal of Sociology': 'Am. J. Sociol.',
 'Social Forces': 'Social Forces',
 'Science': 'Science',
 'Nature': 'Nature',
 'PNAS': 'PNAS',
 'The New England Journal of Medicine': 'N. Engl. J. Med.',
 'Journal of the American Chemical Society': 'J. Am. Chem. Soc.',
 'Physical Review Letters': 'Phys. Rev. Lett.',
 'Transactions of the American Mathematical Society': 'Trans. Am. Math. Soc.',
 'Annals of Mathematics': 'Ann. Math.',
 'Inventiones Mathematicae': 'Invent. Math.',
 'Communications of The ACM': 'Commun. ACM',
 'ACM Conference on Human Factors in Computing Systems (CHI)': 'ACM CHI',
 'The American Historical Review': 'Am. Hist. Rev.',
 'Comparative Studies in Society and History': 'Comp. Stud. Soc. Hist.',
 'The Journal of American History': 'J. Am. Hist.',
 'Mind': 'Mind',
 'Philosophical Studies': 'Philos. Stud.',
 'The Philosophical Review': 'Philos. Rev.',
 'USENIX Security Symposium (UsenixSec)': 'UsenixSec',
 'The Accounting Review': 'Account. Rev.',
 'Journal of Personality and Social Psychology': 'J. Pers. Soc. Psychol.',
 'Cell': 'Cell'}